### ISSUE TITLE
Dependency on libudev-dev

### ISSUE THREAD

**Issue by rluu** [vfilimonov/co2meter#11]
Thank you for the work on this project.  It is running successfully on my Raspberry Pi on Debian Jessie (Linux).  

However, to get it to work, I had to install an additional dependency not mentioned in your documentation.  The pip install of hidapi failed due to not being able to link to the udev library.  
I corrected that by installing Linux package libudev-dev:

```
apt-get install libudev-dev
```

Not sure if you would like to add that information to your README.md, but it may help others.

Kind regards.

**Comment by vfilimonov** [comment]
Sure, thanks for reporting! It's done now.
p.s. it turns out there were a pull request with this change as well, which I unfortunately overlooked before.
