### ISSUE TITLE
bypass_decrypt option in co2meter_server

### ISSUE THREAD

**Issue by Masahiro1** [vfilimonov/co2meter#23]
https://github.com/vfilimonov/co2meter/blob/8a2e12d205a7ac1c0a8fbc7fe885fc60cf2d1d0c/co2meter/server.py#L264

It may be useful to be able to set ``bypass_decrypt`` like below.

```python
mon = co2.CO2monitor(bypass_decrypt=True)
```

---

Thank you for creating such a wonderful library. 
It is very helpful.

**Comment by vfilimonov** [comment]
The argument `--bypass-decrypt` is exposed via command line now (`co2meter_server --bypass-decrypt` or `co2meter_server -b`)

Could you please check the master - if it works on your side?

**Comment by Masahiro1** [comment]
Thank you for the implementation. It worked!
